name = "RBCFlowInRigidTube"
uuid = "fd3e2825-7e96-4de1-bf44-7be031df0283"
authors = ["Ali Gurbuz"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
